language: node_js
node_js:
  - "node"
global:
  - REPO_OWNER=vokal
  - REPO_NAME=TrueColors-LESS
install:
  - npm install -g istanbul
  - npm install
script:
  - chmod +x run-build.sh
  - ./run-build.sh
